services:

  postgres:
    image: postgres:16-alpine
    container_name: se_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - se_network
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: se_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - se_network
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: se_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - se_network
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

volumes:
  postgres_data:
  redis_data:

networks:
  se_network:
    driver: bridge